//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Errors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Errors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Errors", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ERR00000 {
            get {
                return ResourceManager.GetString("ERR00000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ERR00001 {
            get {
                return ResourceManager.GetString("ERR00001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The item specified was not found..
        /// </summary>
        internal static string ERR00002 {
            get {
                return ResourceManager.GetString("ERR00002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The required Id was not specified..
        /// </summary>
        internal static string ERR00003 {
            get {
                return ResourceManager.GetString("ERR00003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The item is null..
        /// </summary>
        internal static string ERR00004 {
            get {
                return ResourceManager.GetString("ERR00004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not authorized to access the resource or action specified..
        /// </summary>
        internal static string ERR00005 {
            get {
                return ResourceManager.GetString("ERR00005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The asset type must be specified..
        /// </summary>
        internal static string ERR00105 {
            get {
                return ResourceManager.GetString("ERR00105", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The contributor must be specified..
        /// </summary>
        internal static string ERR00106 {
            get {
                return ResourceManager.GetString("ERR00106", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Difficulty rating must be between 1 and 5 if specified..
        /// </summary>
        internal static string ERR00107 {
            get {
                return ResourceManager.GetString("ERR00107", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importance rating must be between 1 and 5 if specified..
        /// </summary>
        internal static string ERR00108 {
            get {
                return ResourceManager.GetString("ERR00108", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passing score must be between 1 and 100 if specified..
        /// </summary>
        internal static string ERR00109 {
            get {
                return ResourceManager.GetString("ERR00109", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset title must be specified and can not exceed 100 characters..
        /// </summary>
        internal static string ERR00110 {
            get {
                return ResourceManager.GetString("ERR00110", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset uri is required..
        /// </summary>
        internal static string ERR00111 {
            get {
                return ResourceManager.GetString("ERR00111", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified uri is too long, please use a url shortening tool such as http://www.bit.ly.
        /// </summary>
        internal static string ERR00112 {
            get {
                return ResourceManager.GetString("ERR00112", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A value must be specified for a subject, it&apos;s used like a hashtag..
        /// </summary>
        internal static string ERR00200 {
            get {
                return ResourceManager.GetString("ERR00200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The description must be less than 4000 characters long..
        /// </summary>
        internal static string ERR00201 {
            get {
                return ResourceManager.GetString("ERR00201", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The title must be less than 100 characters long..
        /// </summary>
        internal static string ERR00202 {
            get {
                return ResourceManager.GetString("ERR00202", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The description must be less than 4000 characters long..
        /// </summary>
        internal static string ERR00301 {
            get {
                return ResourceManager.GetString("ERR00301", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The title must be less than 100 characters long..
        /// </summary>
        internal static string ERR00302 {
            get {
                return ResourceManager.GetString("ERR00302", resourceCulture);
            }
        }
    }
}
